final update
Givoxs/CSSGrid pull request #1
Opened 2021-12-11 11:44 UTC by Givoxs

2021-12-12 10:24 UTC, ikegrobben requested changes
Als oefening voor github pas mijn comments aan en upload het

2021-12-12 10:24 UTC, ikegrobben commented on styles.css
> +@media screen and (min-width:576px) {
Normaal gezien gaan media queries in een apart bestand. Maar in dit geval zou ik of je media querie bovenaan of onderaan zetten.

2021-12-12 10:24 UTC, ikegrobben commented on index.html
> +
Vanaf regel 20 heb je 4 wit regels. Beetje veel!

2021-12-13 08:59 UTC, Givoxs commented on index.html
> +
Yes, ik pas het aan!

2021-12-13 09:00 UTC, Givoxs commented on styles.css
> +@media screen and (min-width:576px) {
aangepast

2021-12-17 12:45 UTC, Hyximio commented on index.html
> +<section class="container">
Is niet fout maar wellicht was een div logischer geweest als container. Mocht je een CSS style toepassen voor de dit type section neemt hij deze container nu ook mee
```suggestion
<div class="container">
```
Handig dat je zo een suggestie kan geven. Al zal het ook afgesloten moeten worden met div mocht dit worden doorgevoerd.

2021-12-17 12:48 UTC, Hyximio commented on styles.css
> +        grid-template-rows: 50px auto 50px 50px 50px 50px 50px;
5x 50px kan ook als repeat( 5, 50px ).
```suggestion
        grid-template-rows: 50px auto repeat( 5, 50px );
```

2021-12-17 13:11 UTC, Hyximio requested changes
Ziet er allemaal netjes uit en het werkt foutloos. Sommige feedback heb ik als single comment gestuurd en andere als review. Nog een beetje uitproberen voor mij hoe dit allemaal werkt.
Al met al... Lekker bezig geweest!

2021-12-17 13:11 UTC, Hyximio commented on styles.css
> +            "blockf blockf blockf"
Wellicht als je de block-namen korter had gemaakt met 1 char zou het overzichtelijker en makkelijker leesbaar zijn. Ook zou het daardoor in lijn blijven en netjes onder elkaar staan als je lege grid areas gebruikt

2021-12-17 13:11 UTC, Hyximio commented on styles.css
> +    }
1 tab teveel
```suggestion
#block-a {
    grid-area: blocka;
}
```

2021-12-17 13:11 UTC, Hyximio commented on styles.css
> +        grid-template-rows: 50px auto 50px 50px 50px 50px 50px;
Dit heb ik nu blijkbaar als een single comment gezet ipv een review... geen idee of dit handig is zo

2021-12-17 13:11 UTC, Hyximio commented on styles.css
> +
Ik zou de branch nooit iets met 'Final' in de benaming geven. Ik zou eerder met versie nummers werken. bijv. 'Update v01'. Mocht er dan toch iets van een nieuwe branch komen word de naam niet 'Real final update' of ' final final '... :p In dit geval was wellicht iets van 'uitwerkingen' voldoende geweest.

2021-12-20 12:04 UTC, Givoxs commented on styles.css
> +        grid-template-rows: 50px auto 50px 50px 50px 50px 50px;
Handig als je wat verder bent en meer dan de basis beheerst, zoals jij denk ik dan wel doet haha. Maar goede tip!

2021-12-20 12:05 UTC, Givoxs commented on styles.css
> +            "blockf blockf blockf"
yes, je hebt gelijk

2021-12-20 12:05 UTC, merged